description: A subcellular location, cell type or gross anatomical part
display_name: anatomical entity
document_category: anatomical entity
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
- display_name: in_taxon
  id: in_taxon
  property: []
id: anatomical entity
schema_generating: true
weight: 20
