description: null
display_name: association result set
document_category: association result set
fields:
- cardinality: multi
  description: null
  display_name: associations
  id: associations
  property: []
id: association result set
schema_generating: true
weight: 20
