description: null
display_name: association result set
document_category: association result set
fields:
- cardinality: multi
  description: null
  display_name: associations
  id: associations
  property: []
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
id: association result set
schema_generating: true
weight: 20
