description: A property or characteristic of an entity
display_name: attribute
document_category: attribute
fields:
- {description: holds between two classes where the domain class is a specialization
    of the range class, display_name: subclass of, id: subclass_of}
id: attribute
schema_generating: true
weight: 20
