description: this serves as exemplar for the time being, corresponding to the bioentity
  document type in amigo, which has a single entry per bioentity, with associated
  GO information
display_name: bioentity with go terms
document_category: bioentity with go terms
fields:
- description: Ancestors (reflexive) of the object field following is_a (subClassOf)
    and part-of links. This is typically used as a query constraint and for faceting.
    The combination of is_a and part of is a common pattern, and can be used in gene
    expression queries (finding genes that are expressed in a structure, a subtype,
    or a part of that structure) or in GO queries (in any of the three branches of
    GO)
  display_name: isa partof closure
  id: isa_partof_closure
  property: []
- description: Ancestors (reflexive) of the object field following is_a (subClassOf),
    part-of and regulates (including positive and negative) relationships. This is
    typically used as a query constraint and for faceting where the range is a biological
    process
  display_name: regulates closure
  id: regulates_closure
  property: []
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
- display_name: full_name
  id: full_name
  property: []
- display_name: systematic_synonym
  id: systematic_synonym
  property: []
id: bioentity with go terms
schema_generating: true
weight: 20
