description: this serves as exemplar for the time being, corresponding to the bioentity
  document type in amigo, which has a single entry per bioentity, with associated
  GO information
display_name: bioentity with go terms
document_category: bioentity with go terms
fields:
- display_name: in_family
  id: in_family
  property: []
- display_name: isa_partof_closure
  id: isa_partof_closure
  property: []
- display_name: regulates_closure
  id: regulates_closure
  property: []
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: bioentity with go terms
schema_generating: true
weight: 20
