display_name: biological sex
document_category: biological sex
fields:
- {description: holds between two classes where the domain class is a specialization
    of the range class, display_name: subclass of, id: subclass_of}
id: biological_sex
schema_generating: true
weight: 20
