description: null
display_name: biosample
document_category: biosample
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
- display_name: in_taxon
  id: in_taxon
  property: []
id: biosample
schema_generating: true
weight: 20
