description: may be a chemical entity or a formulation with a chemical entity as active
  ingredient, or a complex material with multiple chemical entities as part
display_name: chemical substance
document_category: chemical substance
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: chemical substance
schema_generating: true
weight: 20
