description: An interaction between a chemical entity and a phenotype or disease,
  where the presence of the chemical gives rise to or exacerbates the phenotype
display_name: chemical to disease or phenotypic feature association
document_category: chemical to disease or phenotypic feature association
fields:
- description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: association type
  id: association_type
  property: []
- description: connects an association to the subject of the association. For example,
    in a gene-to-phenotype association, the gene is subject and phenotype is object.
  display_name: subject
  id: subject
  property: []
- description: if set to true, then the association is negated i.e. is not true
  display_name: negated
  id: negated
  property: []
- description: the relationship type by which a subject is connected to an object
    in an association
  display_name: relation
  id: relation
  property: []
- description: connects an association to the object of the association. For example,
    in a gene-to-phenotype association, the gene is subject and phenotype is object.
  display_name: object
  id: object
  property: []
- cardinality: multi
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: qualifiers
  id: qualifiers
  property: []
- cardinality: multi
  description: connects an association to publications supporting the association
  display_name: publications
  id: publications
  property: []
- description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  id: provided_by
  property: []
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
id: chemical to disease or phenotypic feature association
schema_generating: true
weight: 20
