description: null
display_name: cohort
document_category: cohort
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
id: cohort
schema_generating: true
weight: 20
