description: null
display_name: condition or phenotypic feature
document_category: condition or phenotypic feature
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
- display_name: in_taxon
  id: in_taxon
  property: []
id: condition or phenotypic feature
schema_generating: true
weight: 20
