description: null
display_name: condition or phenotypic condition
document_category: condition or phenotypic condition
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: condition or phenotypic condition
schema_generating: true
weight: 20
