description: null
display_name: condition or phenotypic condition
document_category: condition or phenotypic condition
fields: []
id: condition or phenotypic condition
schema_generating: true
weight: 20
