description: A stage of development or growth of an organism, including post-natal
  adult stages
display_name: developmental stage
document_category: developmental stage
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: developmental stage
schema_generating: true
weight: 20
