description: null
display_name: disease
document_category: disease
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
id: disease
schema_generating: true
weight: 20
