description: null
display_name: disease to phenotypic feature denormalized association
document_category: disease to phenotypic feature denormalized association
fields: []
id: disease to phenotypic feature denormalized association
schema_generating: true
weight: 20
