description: An association between a disease and a phenotypic feature in which the
  phenotypic feature is associated with the disease in some way
display_name: disease to phenotypic feature association
document_category: disease to phenotypic feature association
fields: []
id: disease to phenotypic feature association
schema_generating: true
weight: 20
