description: A feature of the environment of an organism that influences one or more
  phenotypic features of that organism, potentially mediated by genes
display_name: environmental feature
document_category: environmental feature
fields: []
id: environmental feature
schema_generating: true
weight: 20
