description: null
display_name: environmental feature
document_category: environmental feature
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
id: environmental feature
schema_generating: true
weight: 20
