description: Evidence that supports an association
display_name: evidence type
document_category: evidence type
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: evidence type
schema_generating: true
weight: 20
