description: describes the frequency of occurrence of an event or condition
display_name: frequency value
document_category: frequency value
fields:
- {description: holds between two classes where the domain class is a specialization
    of the range class, display_name: subclass of, id: subclass_of}
id: frequency_value
schema_generating: true
weight: 20
