description: null
display_name: gene product
document_category: gene product
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
id: gene product
schema_generating: true
weight: 20
