description: An interaction between two genes or two gene products. May be physical
  (e.g. protein binding) or genetic (between genes). May be symmetric (e.g. protein
  interaction) or directed (e.g. phosphorylation)
display_name: gene or protein interaction
document_category: gene or protein interaction
fields:
- description: null
  display_name: id
  id: id
  property: []
- display_name: type
  id: type
  property: []
- description: connects an association to the subject
  display_name: subject
  id: subject
  property: []
- description: if set then the association is negated
  display_name: negated
  id: negated
  property: []
- description: the relationship type by which a subject is connected to an object
    in an association
  display_name: relation
  id: relation
  property: []
- description: connects an association to the object
  display_name: object
  id: object
  property: []
- cardinality: multi
  description: qualifiers
  display_name: qualifiers
  id: qualifiers
  property: []
- display_name: subject_extension
  id: subject_extension
  property: []
- display_name: object_extension
  id: object_extension
  property: []
- display_name: publications
  id: publications
  property: []
- display_name: provided_by
  id: provided_by
  property: []
- display_name: evidence_graph
  id: evidence_graph
  property: []
- display_name: evidence_type
  id: evidence_type
  property: []
- display_name: evidence
  id: evidence
  property: []
id: gene or protein interaction
schema_generating: true
weight: 20
