description: a grouping of multiple genes or gene products related by common descent
display_name: gene family
document_category: gene family
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: gene family
schema_generating: true
weight: 20
