description: an ontology class that describes a functional aspect of a gene, gene
  prodoct or complex
display_name: gene ontology class
document_category: gene ontology class
fields:
- {description: holds between two classes where the domain class is a specialization
    of the range class, display_name: subclass of, id: subclass_of}
id: gene_ontology_class
schema_generating: true
weight: 20
