description: null
display_name: gene
document_category: gene
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: gene
schema_generating: true
weight: 20
