description: null
display_name: gene
document_category: gene
fields:
- display_name: full_name
  id: full_name
  property: []
- display_name: systematic_synonym
  id: systematic_synonym
  property: []
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: gene
schema_generating: true
weight: 20
