description: An interaction between two genes or two gene products. May be physical
  (e.g. protein binding) or genetic (between genes). May be symmetric (e.g. protein
  interaction) or directed (e.g. phosphorylation)
display_name: gene or protein interaction
document_category: gene or protein interaction
fields: []
id: gene or protein interaction
schema_generating: true
weight: 20
