description: An association between a gene and an expression site, possibly qualified
  by stage/timing info
display_name: gene to expression site association
document_category: gene to expression site association
fields: []
id: gene to expression site association
schema_generating: true
weight: 20
