description: A homology association between two genes. May be orthology (in which
  case the species of subject and object should differ) or paralogy (in which case
  the species may be the same)
display_name: gene to gene homology association
document_category: gene to gene homology association
fields: []
id: gene to gene homology association
schema_generating: true
weight: 20
