description: An interaction between two genes or two gene products. May be physical
  (e.g. protein binding) or genetic (between genes). May be symmetric (e.g. protein
  interaction) or directed (e.g. phosphorylation)
display_name: gene or protein interaction
document_category: gene or protein interaction
fields:
- description: null
  display_name: id
  id: id
  property: []
- display_name: type
  id: type
  property: []
- description: connects an association to the subject of the association. For example,
    in a gene-to-phenotype association, the gene is subject and phenotype is object.
  display_name: subject
  id: subject
  property: []
- description: if set to true, then the association is negated i.e. is not true
  display_name: negated
  id: negated
  property: []
- description: the relationship type by which a subject is connected to an object
    in an association
  display_name: relation
  id: relation
  property: []
- description: connects an association to the object of the association. For example,
    in a gene-to-phenotype association, the gene is subject and phenotype is object.
  display_name: object
  id: object
  property: []
- cardinality: multi
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: qualifiers
  id: qualifiers
  property: []
- description: Additional relationships that are true of the subject in the context
    of the association. For example, if the subject is a gene product in a functional
    association, the subject extensions may represent  an isoform or a specific post-translational
    state
  display_name: subject extensions
  id: subject_extensions
  property: []
- description: Additional relationships that are true of the object in the context
    of the association. For example, if the object is an anatomical term in an expression
    association, the object extensions may include part-of links
  display_name: object extensions
  id: object_extensions
  property: []
- cardinality: multi
  description: connects an association to publications supporting the association
  display_name: publications
  id: publications
  property: []
- description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  id: provided_by
  property: []
- display_name: has evidence graph
  id: has_evidence_graph
  property: []
- description: connects an association to the class of evidence used
  display_name: has evidence type
  id: has_evidence_type
  property: []
- description: connects an association to an instance of supporting evidence
  display_name: has evidence
  id: has_evidence
  property: []
id: gene or protein interaction
schema_generating: true
weight: 20
