description: a union of genes or gene products. Frequently an identifier for one will
  be used as proxy for another
display_name: gene or gene product
document_category: gene or gene product
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: gene or gene product
schema_generating: true
weight: 20
