description: An attribute corresponding to the genotypic sex of the individual, based
  upon genotypic composition of sex chromosomes.
display_name: genotypic sex
document_category: genotypic sex
fields:
- {description: holds between two classes where the domain class is a specialization
    of the range class, display_name: subclass of, id: subclass_of}
id: genotypic_sex
schema_generating: true
weight: 20
