description: null
display_name: genotype
document_category: genotype
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: genotype
schema_generating: true
weight: 20
