description: null
display_name: individual organism
document_category: individual organism
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: individual organism
schema_generating: true
weight: 20
