description: A stage of development or growth of an organism, including post-natal
  adult stages
display_name: life stage
document_category: life stage
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
- description: connects a thing to a class representing a taxon
  display_name: in taxon
  id: in_taxon
  property: []
id: life stage
schema_generating: true
weight: 20
