description: null
display_name: macromolecular complex
document_category: macromolecular complex
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: macromolecular complex
schema_generating: true
weight: 20
