description: A gene, gene product, small molecule or macromolecule (including protein
  complex)
display_name: molecular entity
document_category: molecular entity
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: molecular entity
schema_generating: true
weight: 20
