description: A gene, gene product, small molecule or macromolecule (including protein
  complex)
display_name: molecular entity
document_category: molecular entity
fields: []
id: molecular entity
schema_generating: true
weight: 20
