description: null
display_name: molecular event
document_category: molecular event
fields:
- display_name: enabled by
  id: enabled_by
  property: []
- display_name: part of
  id: part_of
  property: []
- display_name: occurs in
  id: occurs_in
  property: []
- display_name: upstream causal relationship
  id: upstream_causal_relationship
  property: []
- display_name: downstream causal relationship
  id: downstream_causal_relationship
  property: []
id: molecular event
schema_generating: true
weight: 20
