description: null
display_name: molecular event
document_category: molecular event
fields:
- display_name: enabled by
  id: enabled by
  property: []
- display_name: part of
  id: part of
  property: []
- display_name: occurs in
  id: occurs in
  property: []
- display_name: upstream causal relationship
  id: upstream causal relationship
  property: []
- display_name: downstream causal relationship
  id: downstream causal relationship
  property: []
id: molecular event
schema_generating: true
weight: 20
