description: a databased entity or concept/class
display_name: named thing
document_category: named thing
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: named thing
schema_generating: true
weight: 20
