description: The age group in which manifestations appear
display_name: onset
document_category: onset
fields:
- {description: holds between two classes where the domain class is a specialization
    of the range class, display_name: subclass of, id: subclass_of}
id: onset
schema_generating: true
weight: 20
