description: a concept or class in an ontology, vocabulary or thesaurus
display_name: ontology class
document_category: ontology class
fields: []
id: ontology class
schema_generating: true
weight: 20
