description: a concept or class in an ontology, vocabulary or thesaurus
display_name: ontology class
document_category: ontology class
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: ontology class
schema_generating: true
weight: 20
