description: null
display_name: phenotypic feature
document_category: phenotypic feature
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: phenotypic feature
schema_generating: true
weight: 20
