description: null
display_name: population of individual organisms
document_category: population of individual organisms
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: population of individual organisms
schema_generating: true
weight: 20
