description: null
display_name: population of individual organisms
document_category: population of individual organisms
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
- display_name: in_taxon
  id: in_taxon
  property: []
id: population of individual organisms
schema_generating: true
weight: 20
