description: null
display_name: property value pair
document_category: property value pair
fields:
- description: the relationship type by which a subject is connected to an object
    in an association
  display_name: relation
  id: relation
  property: []
- description: The value in a property-value tuple
  display_name: filler
  id: filler
  property: []
id: property value pair
schema_generating: true
weight: 20
