description: null
display_name: property value pair
document_category: property value pair
fields:
- description: the relationship type by which a subject is connected to an object
    in an association
  display_name: relation
  id: relation
  property: []
- display_name: value
  id: value
  property: []
id: property value pair
schema_generating: true
weight: 20
