description: null
display_name: protein
document_category: protein
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: protein
schema_generating: true
weight: 20
