description: null
display_name: RNA product
document_category: RNA product
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: RNA product
schema_generating: true
weight: 20
