description: A genomic feature representing one of a set of coexisting sequence variants
  at a particular genomic locus.
display_name: sequence variant
document_category: sequence variant
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: null
  display_name: label
  id: label
  property: []
id: sequence variant
schema_generating: true
weight: 20
