display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- specificity quantifier
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- specificity quantifier
id: specificity_quantifier
schema_generating: true
weight: 20
