description: A mixin that can be used on any entity with a taxon
display_name: thing with taxon
document_category: thing with taxon
fields:
- description: null
  display_name: in taxon
  id: in_taxon
  property: []
id: thing with taxon
schema_generating: true
weight: 20
