display_name: zygosity
document_category: zygosity
fields:
- {description: holds between two classes where the domain class is a specialization
    of the range class, display_name: subclass of, id: subclass_of}
id: zygosity
schema_generating: true
weight: 20
