display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- molecular event
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- molecular event
fields:
- display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - enabled by
  id: enabled_by
- description: holds between parts and wholes (material entities or processes)
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - part of
  id: part_of
- description: holds between a process and a material entity or site within which
    the process occurs
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - occurs in
  id: occurs_in
- display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - upstream causal relationship
  id: upstream_causal_relationship
- display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - downstream causal relationship
  id: downstream_causal_relationship
id: molecular_event
schema_generating: true
weight: 20
