display_name: molecular event
document_category: molecular event
fields:
- {display_name: enabled by, id: enabled_by}
- {description: holds between parts and wholes (material entities or processes), display_name: part
    of, id: part_of}
- {description: holds between a process and a material entity or site within which
    the process occurs, display_name: occurs in, id: occurs_in}
- {display_name: upstream causal relationship, id: upstream_causal_relationship}
- {display_name: downstream causal relationship, id: downstream_causal_relationship}
id: molecular_event
schema_generating: true
weight: 20
