display_name: property value pair
document_category: property value pair
fields:
- {description: the relationship type by which a subject is connected to an object
    in an association, display_name: relation, id: relation}
- {description: The value in a property-value tuple, display_name: filler, id: filler}
id: property_value_pair
schema_generating: true
weight: 20
