description: An RNA synthesized on a DNA or RNA template by an RNA polymerase
display_name: transcript
document_category: transcript
fields:
- {description: A unique identifier for a thing. Must be either a CURIE shorthand
    for a URI or a complete URI, display_name: id, id: id}
- {description: A human-readable name for a thing, display_name: name, id: name}
- {description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class. In a neo4j database
    this MAY correspond to the neo4j label tag, display_name: category, id: category}
- {description: A grouping for any relationship type that holds between any two things,
  display_name: related to, id: related_to}
- {description: A grouping for any property that holds between a node and a value,
  display_name: node property, id: node_property}
- {description: An IRI for the node. This is determined by the id using expansion
    rules., display_name: iri, id: iri}
- {description: a long-form human readable name for a thing, display_name: full name,
  id: full_name}
- {description: a human-readable description of a thing, display_name: description,
  id: description}
- {description: more commonly used for gene symbols in yeast, display_name: systematic
    synonym, id: systematic_synonym}
- {description: 'holds between a biological entity and a phenotype, where a phenotype
    is construed broadly as any kind of quality of an organism part, a collection
    of these qualities, or a change in quality or qualities (e.g. abnormally increased
    temperature). ', display_name: has phenotype, id: has_phenotype}
- {description: connects a thing to a class representing a taxon, display_name: in
    taxon, id: in_taxon}
- {cardinality: multi, description: 'Ancestors (reflexive) of the object field following
    is_a (subClassOf) and part-of links. This is typically used as a query constraint
    and for faceting. The combination of is_a and part of is a common pattern, and
    can be used in gene expression queries (finding genes that are expressed in a
    structure, a subtype, or a part of that structure) or in GO queries (in any of
    the three branches of GO)', display_name: isa partof closure, id: isa_partof_closure}
- {cardinality: multi, description: 'parent field for fields used for storing the
    label of the closure concept. See also: closure concept field', display_name: isa
    partof closure label, id: isa_partof_closure_label}
- {cardinality: multi, description: 'Ancestors (reflexive) of the object field following
    is_a (subClassOf), part-of and regulates (including positive and negative) relationships.
    This is typically used as a query constraint and for faceting where the range
    is a biological process', display_name: regulates closure, id: regulates_closure}
- {cardinality: multi, description: 'parent field for fields used for storing the
    label of the closure concept. See also: closure concept field', display_name: regulates
    closure label, id: regulates_closure_label}
- {description: holds between two entities that make physical contact as part of some
    interaction, display_name: molecularly interacts with, id: molecularly_interacts_with}
- {description: 'describes an entity that has a direct affect on the state or quality
    of another existing entity. Use of the ''affects'' predicate implies that the
    affected entity already exists, unlike predicates such as ''affects risk for''
    and ''prevents, where the outcome is something that may or may not come to be.',
  display_name: 'regulates, entity to entity', id: regulates_entity_to_entity}
- {description: 'holds between a measurable molecular entity and a disease or phenotypic
    feature, where the entity is used as an indicator of the presence or state of
    the disease or feature.', display_name: biomarker for, id: biomarker_for}
- {description: connects a genomic feature to its sequence, display_name: has biological
    sequence, id: has_biological_sequence}
id: transcript
schema_generating: true
weight: 20
