description: null
display_name: biological entity
document_category: biological entity
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
id: biological entity
schema_generating: true
weight: 20
