description: One or more causally connected executions of molecular functions
display_name: biological process
document_category: biological process
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
id: biological process
schema_generating: true
weight: 20
