description: A location in or around a cell
display_name: cellular component
document_category: cellular component
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
- description: connects a thing to a class representing a taxon
  display_name: in taxon
  id: in_taxon
  property: []
id: cellular component
schema_generating: true
weight: 20
