description: null
display_name: clinical trial
document_category: clinical trial
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
id: clinical trial
schema_generating: true
weight: 20
