description: null
display_name: clinical intervention
document_category: clinical intervention
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
id: clinical intervention
schema_generating: true
weight: 20
