description: Any entity or process that exists in the clinical domain and outside
  the biological realm. Diseases are placed under biological entities
display_name: clinical entity
document_category: clinical entity
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
id: clinical entity
schema_generating: true
weight: 20
