description: null
display_name: environmental process
document_category: environmental process
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
id: environmental process
schema_generating: true
weight: 20
