description: A feature of the environment of an organism that influences one or more
  phenotypic features of that organism, potentially mediated by genes
display_name: environment
document_category: environment
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
id: environment
schema_generating: true
weight: 20
