description: A region of the transcript sequence within a gene which is not removed
  from the primary RNA transcript by RNA splicing
display_name: exon
document_category: exon
fields:
- description: connects a genomic feature to its sequence
  display_name: has biological sequence
  id: has_biological_sequence
  property: []
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
- description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class
  display_name: category
  id: category
  property: []
- description: connects a thing to a class representing a taxon
  display_name: in taxon
  id: in_taxon
  property: []
id: exon
schema_generating: true
weight: 20
