description: A region of the transcript sequence within a gene which is not removed
  from the primary RNA transcript by RNA splicing
display_name: exon
document_category: exon
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
- description: connects a thing to a class representing a taxon
  display_name: in taxon
  id: in_taxon
  property: []
id: exon
schema_generating: true
weight: 20
