description: describes the frequency of occurrence of an event or condition
display_name: frequency value
document_category: frequency value
fields: []
id: frequency value
schema_generating: true
weight: 20
