description: an ontology class that describes a functional aspect of a gene, gene
  prodoct or complex
display_name: gene ontology class
document_category: gene ontology class
fields: []
id: gene ontology class
schema_generating: true
weight: 20
