description: An information content entity that describes a genome by specifying the
  total variation in genomic sequence and/or gene expression, relative to some extablished
  background
display_name: genotype
document_category: genotype
fields:
- description: null
  display_name: has zygosity
  id: has_zygosity
  property: []
- description: connects a genomic feature to its sequence
  display_name: has biological sequence
  id: has_biological_sequence
  property: []
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
- description: connects a thing to a class representing a taxon
  display_name: in taxon
  id: in_taxon
  property: []
id: genotype
schema_generating: true
weight: 20
