description: A relation used for homology
display_name: homology relationship type
document_category: homology relationship type
fields: []
id: homology relationship type
schema_generating: true
weight: 20
