description: A relation used for interaction relationships
display_name: interaction relationship type
document_category: interaction relationship type
fields: []
id: interaction relationship type
schema_generating: true
weight: 20
