description: A stage of development or growth of an organism, including post-natal
  adult stages
display_name: life stage
document_category: life stage
fields:
- description: A unique identifier for a thing. Must be either a CURIE shorthand for
    a URI or a complete URI
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: name
  id: name
  property: []
- description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class. In a neo4j database
    this MAY correspond to the neo4j label tag
  display_name: category
  id: category
  property: []
- description: connects a thing to a class representing a taxon
  display_name: in taxon
  id: in_taxon
  property: []
id: life stage
schema_generating: true
weight: 20
