description: An execution of a molecular function
display_name: molecular activity
document_category: molecular activity
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
- description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class
  display_name: category
  id: category
  property: []
id: molecular activity
schema_generating: true
weight: 20
