description: Any entity or process that exists at the level of the whole planet
display_name: planetary entity
document_category: planetary entity
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
id: planetary entity
schema_generating: true
weight: 20
