description: Any entity or process that exists at the level of the whole planet
display_name: planetary entity
document_category: planetary entity
fields:
- description: A unique identifier for a thing. Must be either a CURIE shorthand for
    a URI or a complete URI
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: name
  id: name
  property: []
- description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class. In a neo4j database
    this MAY correspond to the neo4j label tag
  display_name: category
  id: category
  property: []
id: planetary entity
schema_generating: true
weight: 20
