display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- property value pair
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- property value pair
fields:
- description: the relationship type by which a subject is connected to an object
    in an association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - relation
  id: relation
- description: The value in a property-value tuple
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - filler
  id: filler
id: property_value_pair
schema_generating: true
weight: 20
