description: A gene product that is composed of a chain of amino acid sequences and
  is produced by ribosome-mediated translation of mRNA
display_name: protein
document_category: protein
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
- description: connects a thing to a class representing a taxon
  display_name: in taxon
  id: in_taxon
  property: []
id: protein
schema_generating: true
weight: 20
