description: Any published piece of information. Can refer to a whole publication,
  or to a part of it (e.g. a figure, figure legend, or section highlighted by NLP).
  The scope is intended to be general and include information published on the web
  as well as journals.
display_name: publication
document_category: publication
fields:
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
- description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class
  display_name: category
  id: category
  property: []
id: publication
schema_generating: true
weight: 20
