description: null
display_name: RNA product
document_category: RNA product
fields:
- description: connects a genomic feature to its sequence
  display_name: has biological sequence
  id: has_biological_sequence
  property: []
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
- description: connects a thing to a class representing a taxon
  display_name: in taxon
  id: in_taxon
  property: []
id: RNA product
schema_generating: true
weight: 20
