description: Represents a protein that is a specific isoform of the canonical or reference
  RNA
display_name: RNA product isoform
document_category: RNA product isoform
fields:
- {description: A unique identifier for a thing. Must be either a CURIE shorthand
    for a URI or a complete URI, display_name: id, id: id}
- {description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class. In a neo4j database
    this MAY correspond to the neo4j label tag, display_name: category, id: category}
- {cardinality: multi, description: 'An alternate identifier for the entity, provided
    by the source database', display_name: has alternate identifier, id: has_alternate_identifier}
- {cardinality: multi, description: 'A database cross-reference for the entity, provided
    by a separate database', display_name: has xref, id: has_xref}
- {cardinality: multi, description: Alternate labels for an entity, display_name: has
    synonym, id: has_synonym}
- {description: A grouping for any relationship type that holds between any two things,
  display_name: related to, id: related_to}
- {description: A grouping for any property that holds between a node and a value,
  display_name: node property, id: node_property}
- {description: An IRI for the node. This is determined by the id using expansion
    rules., display_name: iri, id: iri}
- {description: a long-form human readable name for a thing, display_name: full name,
  id: full_name}
- {description: a human-readable description of a thing, display_name: description,
  id: description}
- {description: more commonly used for gene symbols in yeast, display_name: systematic
    synonym, id: systematic_synonym}
- {description: 'holds between a biological entity and a phenotype, where a phenotype
    is construed broadly as any kind of quality of an organism part, a collection
    of these qualities, or a change in quality or qualities (e.g. abnormally increased
    temperature). ', display_name: has phenotype, id: has_phenotype}
- {description: connects a thing to a class representing a taxon, display_name: in
    taxon, id: in_taxon}
- {description: holds between two entities that make physical contact as part of some
    interaction, display_name: molecularly interacts with, id: molecularly_interacts_with}
- {description: 'describes an entity that has a direct affect on the state or quality
    of another existing entity. Use of the ''affects'' predicate implies that the
    affected entity already exists, unlike predicates such as ''affects risk for''
    and ''prevents, where the outcome is something that may or may not come to be.',
  display_name: 'regulates, entity to entity', id: regulates_entity_to_entity}
- {description: 'holds between a measurable molecular entity and a disease or phenotypic
    feature, where the entity is used as an indicator of the presence or state of
    the disease or feature.', display_name: biomarker for, id: biomarker_for}
- {description: connects a genomic feature to its sequence, display_name: has biological
    sequence, id: has_biological_sequence}
- {description: A human-readable name for a thing, display_name: macromolecular machine
    name, id: name}
- {description: holds between two genes or gene products that are part of in the same
    biological pathway, display_name: in pathway with, id: in_pathway_with}
- {description: holds between two genes or gene products that are part of (or code
    for products that are part of) in the same macromolecular complex, display_name: in
    complex with, id: in_complex_with}
- {description: 'holds between two genes or gene products that are expressed in the
    same cell type or population ', display_name: in cell population with, id: in_cell_population_with}
- {description: holds between a gene or gene product and an anatomical entity in which
    it is expressed, display_name: expressed in, id: expressed_in}
id: RNA_product_isoform
schema_generating: true
weight: 20
