description: An association that includes flattened inlined objects, such as subject_taxon_closure
display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- taxon closure mixin
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- taxon closure mixin
fields:
- description: the taxonomic class of the entity in the object slot
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - subject taxon
  id: subject_taxon
- display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - subject taxon label
  id: subject_taxon_label
- cardinality: multi
  description: The taxon class or ancestor class for the subject
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - subject taxon closure
  id: subject_taxon_closure
- cardinality: multi
  description: The label for the taxon class or ancestor class for the subject
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - subject taxon closure label
  id: subject_taxon_closure_label
- description: the taxonomic class of the entity in the object slot
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - object taxon
  id: object_taxon
- display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - object taxon label
  id: object_taxon_label
- cardinality: multi
  description: The taxon class or ancestor class for the object
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - object taxon closure
  id: object_taxon_closure
- cardinality: multi
  description: The label for the taxon class or ancestor class for the object
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - object taxon closure label
  id: object_taxon_closure_label
id: taxon_closure_mixin
schema_generating: true
weight: 20
