description: An RNA synthesized on a DNA or RNA template by an RNA polymerase
display_name: transcript
document_category: transcript
fields:
- description: connects a genomic feature to its sequence
  display_name: has biological sequence
  id: has_biological_sequence
  property: []
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
- description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class
  display_name: category
  id: category
  property: []
- description: connects a thing to a class representing a taxon
  display_name: in taxon
  id: in_taxon
  property: []
id: transcript
schema_generating: true
weight: 20
