description: A treatment is targeted at a disease or phenotype and may involve multiple
  drug 'exposures'
display_name: treatment
document_category: treatment
fields:
- description: null
  display_name: treats
  id: treats
  property: []
- cardinality: multi
  description: null
  display_name: has exposure parts
  id: has_exposure_parts
  property: []
- description: null
  display_name: id
  id: id
  property: []
- description: A human-readable name for a thing
  display_name: label
  id: label
  property: []
- description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class
  display_name: category
  id: category
  property: []
id: treatment
schema_generating: true
weight: 20
