description: Used to characterize and specify the phenotypic abnormalities defined
  in the Phenotypic abnormality subontology, with respect to severity, laterality,
  age of onset, and other aspects
display_name: clinical modifier
document_category: clinical modifier
fields:
- {description: holds between two classes where the domain class is a specialization
    of the range class, display_name: subclass of, id: subclass_of}
id: clinical_modifier
schema_generating: true
weight: 20
