display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName [frequency
    quantifier]
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName [frequency
    quantifier]
fields:
- description: number of things with a particular property
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [has count]
  id: has_count
- description: total number of things in a particular reference set
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [has total]
  id: has_total
- description: A grouping for any property that holds between a node and a value
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [has quotient]
  id: has_quotient
- description: equivalent to has quotient multiplied by 100
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [has percentage]
  id: has_percentage
id: frequency_quantifier
schema_generating: true
weight: 20
