description: Qualifier for freqency type associations
display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName [frequency
    qualifier]
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName [frequency
    qualifier]
id: frequency_qualifier
schema_generating: true
weight: 20
