display_name: named graph
document_category: named graph
fields:
- {description: A unique identifier for a thing. Must be either a CURIE shorthand
    for a URI or a complete URI, display_name: id, id: id}
- {description: A human-readable name for a thing, display_name: name, id: name}
- {description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class. In a neo4j database
    this MAY correspond to the neo4j label tag, display_name: category, id: category}
- {description: URI expansion of CURIE, display_name: uri, id: uri}
- {description: A grouping for any relationship type that holds between any two things,
  display_name: related to, id: related_to}
- {description: A grouping for any property that holds between a node and a value,
  display_name: node property, id: node_property}
- {description: An IRI for the node. This is determined by the id using expansion
    rules., display_name: iri, id: iri}
- {description: a long-form human readable name for a thing, display_name: full name,
  id: full_name}
- {description: a human-readable description of a thing, display_name: description,
  id: description}
- {description: more commonly used for gene symbols in yeast, display_name: systematic
    synonym, id: systematic_synonym}
- {description: Narrative text describing the entity, display_name: named graph title,
  id: title}
id: named_graph
schema_generating: true
weight: 20
