display_name: organism taxon
document_category: organism taxon
fields:
- {description: holds between two classes where the domain class is a specialization
    of the range class, display_name: subclass of, id: subclass_of}
id: organism_taxon
schema_generating: true
weight: 20
