description: An attribute corresponding to the phenotypic sex of the individual, based
  upon the reproductive organs present.
display_name: phenotypic sex
document_category: phenotypic sex
fields:
- {description: holds between two classes where the domain class is a specialization
    of the range class, display_name: subclass of, id: subclass_of}
id: phenotypic_sex
schema_generating: true
weight: 20
