description: An OWL property used as an edge label
display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName [relationship
    type]
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName [relationship
    type]
id: relationship_type
schema_generating: true
weight: 20
