display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- senstivity quantifier
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- senstivity quantifier
id: senstivity_quantifier
schema_generating: true
weight: 20
