description: describes the severity of a phenotypic feature or disease
display_name: severity value
document_category: severity value
fields:
- {description: holds between two classes where the domain class is a specialization
    of the range class, display_name: subclass of, id: subclass_of}
id: severity_value
schema_generating: true
weight: 20
