---
name: Codespell

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Codespell
        uses: codespell-project/actions-codespell@v1
        with:
          skip: json-schema,golr-views,graphviz,contrib,docs,tests,java,notebooks,prefix-map,notebooks,biolink,images,biolink-model.g*,biolink-model.o*,biolink-model.s*,biolink-model.t*,biolink-model.p*,context.*
          only_warn: 1
          ignore_words_list: amination,ehr,mor,nin,brite,mirgate,BRITE