---
name: Codespell

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Codespell
        uses: codespell-project/actions-codespell@v1
        with:
          skip: golr-views,graphviz,contrib,docs,tests,java,notebooks,prefix-map,notebooks,biolink,images
          exclude_file: biolink-model.graphql,biolink-model.owl.ttl,biolink-model.proto,biolink-model.shacl.ttl,biolink-model.shex,biolink-model.shexj,biolink-model.ttl,biolink-modeln.*,context.json*
          only_warn: 1